// registry.mjs — financial-services Copilot CLI extension registry.
//
// Exports a flat `tools` array consumed by extension.mjs's joinSession() call,
// plus a `presence` note injected on session start.
//
// Tools are generated by walking the install tree at module-load time:
//   extensions/financial-services/specialists/<slug>/agents/<slug>.md
//                                           /skills/<name>/SKILL.md
//   verticals/<vertical>/skills/<name>/SKILL.md
//   commands/agents/<name>/agent.md
//   commands/skills/<name>/SKILL.md
//
// Each agent/skill markdown file becomes a discovery tool the model can call
// to load its content into context. Naming convention (snake_case, ASCII-safe):
//   fs_<slug>_role
//   fs_<slug>_skill_<name>
//   fs_<vertical>_skill_<name>
//   fs_cmd_<name>          (slash-command agents)
//   fs_cmd_skill_<name>    (slash-command skills)
//
// This pure module (no SDK import) is loaded by extension.mjs which performs
// the actual joinSession call.

import { readFile } from "node:fs/promises";
import { existsSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));

const SPECIALISTS_DIR = join(HERE, "extensions", "financial-services", "specialists");
const VERTICALS_DIR = join(HERE, "verticals");
const CMD_AGENTS_DIR = join(HERE, "commands", "agents");
const CMD_SKILLS_DIR = join(HERE, "commands", "skills");
const INSTRUCTIONS_DIR = join(HERE, "instructions");
const MCP_CONFIG = join(HERE, "mcp", ".mcp.json");

function listDirs(p) {
    if (!existsSync(p)) return [];
    return readdirSync(p, { withFileTypes: true })
        .filter((d) => d.isDirectory())
        .map((d) => d.name);
}

function safeName(s) {
    return s.replaceAll("-", "_").replaceAll(/[^a-zA-Z0-9_]/g, "_");
}

function tool(name, description, handler) {
    return {
        name,
        description,
        parameters: { type: "object", properties: {} },
        skipPermission: true,
        handler,
    };
}

async function loadMd(p) {
    if (!existsSync(p)) {
        return { textResultForLlm: `File not found: ${p}`, resultType: "failure" };
    }
    try {
        return await readFile(p, "utf8");
    } catch (err) {
        return { textResultForLlm: `Failed to read ${p}: ${err.message}`, resultType: "failure" };
    }
}

// ── Discover everything at module load ──────────────────────────────────

const specialists = listDirs(SPECIALISTS_DIR);
const verticals = listDirs(VERTICALS_DIR);
const cmdAgents = listDirs(CMD_AGENTS_DIR);
const cmdSkills = listDirs(CMD_SKILLS_DIR);

const inventory = {
    specialists: specialists.map((slug) => ({
        slug,
        skills: listDirs(join(SPECIALISTS_DIR, slug, "skills")),
    })),
    verticals: verticals.map((v) => ({
        vertical: v,
        skills: listDirs(join(VERTICALS_DIR, v, "skills")),
    })),
    cmdAgents,
    cmdSkills,
};

// ── Build the tool list ─────────────────────────────────────────────────

const builtTools = [];

builtTools.push(
    tool(
        "fs_capabilities",
        "Return the full Claude-for-Financial-Services capability map: every specialist, vertical skill, and slash-command agent/skill available in this extension. Call this first when the user asks what financial-services can do.",
        async () => {
            const lines = ["# Claude for Financial Services — capabilities", ""];
            lines.push(`## Specialists (${inventory.specialists.length})`);
            for (const s of inventory.specialists) {
                const safe = safeName(s.slug);
                lines.push(`- **${s.slug}** — \`fs_${safe}_role\`` +
                    (s.skills.length ? ` · skills: ${s.skills.map((k) => `\`fs_${safe}_skill_${safeName(k)}\``).join(", ")}` : ""));
            }
            lines.push("", `## Verticals (${inventory.verticals.length})`);
            for (const v of inventory.verticals) {
                const safe = safeName(v.vertical);
                lines.push(`- **${v.vertical}** — ${v.skills.length ? v.skills.map((k) => `\`fs_${safe}_skill_${safeName(k)}\``).join(", ") : "(no skills)"}`);
            }
            if (inventory.cmdAgents.length) {
                lines.push("", `## Slash-command agents (${inventory.cmdAgents.length})`);
                for (const a of inventory.cmdAgents) lines.push(`- \`fs_cmd_${safeName(a)}\``);
            }
            if (inventory.cmdSkills.length) {
                lines.push("", `## Slash-command skills (${inventory.cmdSkills.length})`);
                for (const a of inventory.cmdSkills) lines.push(`- \`fs_cmd_skill_${safeName(a)}\``);
            }
            lines.push("", "## How to use",
                "1. Pick a specialist whose domain fits the user request.",
                "2. Call its `_role` tool to load the system prompt and workflow.",
                "3. Call individual `_skill_*` tools for the deliverables they describe.",
                "4. Cite every number; mark unsourced figures `[UNSOURCED]`.");
            return lines.join("\n");
        },
    ),
);

for (const s of inventory.specialists) {
    const safe = safeName(s.slug);
    const agentMd = join(SPECIALISTS_DIR, s.slug, "agents", `${s.slug}.md`);
    builtTools.push(tool(
        `fs_${safe}_role`,
        `Load the ${s.slug} agent system prompt and end-to-end workflow. Call this first when the user wants ${s.slug} work.`,
        () => loadMd(agentMd),
    ));
    for (const skill of s.skills) {
        const safeSkill = safeName(skill);
        const md = join(SPECIALISTS_DIR, s.slug, "skills", skill, "SKILL.md");
        builtTools.push(tool(
            `fs_${safe}_skill_${safeSkill}`,
            `Load the ${skill} skill from the ${s.slug} specialist.`,
            () => loadMd(md),
        ));
    }
}

for (const v of inventory.verticals) {
    const safe = safeName(v.vertical);
    for (const skill of v.skills) {
        const safeSkill = safeName(skill);
        const md = join(VERTICALS_DIR, v.vertical, "skills", skill, "SKILL.md");
        builtTools.push(tool(
            `fs_${safe}_skill_${safeSkill}`,
            `Load the ${skill} skill from the ${v.vertical} vertical.`,
            () => loadMd(md),
        ));
    }
}

for (const a of inventory.cmdAgents) {
    const md = join(CMD_AGENTS_DIR, a, "agent.md");
    builtTools.push(tool(
        `fs_cmd_${safeName(a)}`,
        `Load the ${a} slash-command agent system prompt.`,
        () => loadMd(md),
    ));
}

for (const a of inventory.cmdSkills) {
    const md = join(CMD_SKILLS_DIR, a, "SKILL.md");
    builtTools.push(tool(
        `fs_cmd_skill_${safeName(a)}`,
        `Load the ${a} slash-command skill.`,
        () => loadMd(md),
    ));
}

// AGENTS.md / instructions discovery tool (compliance posture).
builtTools.push(tool(
    "fs_instructions",
    "Load the financial-services compliance posture (AGENTS.md) and ambient guardrails. Useful when you need to confirm what disclaimers, sourcing, or audit-trail rules apply.",
    async () => {
        const agentsMd = join(INSTRUCTIONS_DIR, "AGENTS.md");
        if (!existsSync(agentsMd)) {
            return { textResultForLlm: "instructions/AGENTS.md missing in install.", resultType: "failure" };
        }
        return readFile(agentsMd, "utf8");
    },
));

// MCP discovery — read-only listing of the user's enabled MCP connectors.
builtTools.push(tool(
    "fs_mcp_status",
    "Report which Claude-for-Financial-Services MCP connectors are currently enabled (factset, daloopa, lseg, sp-global, ...) per the user's mcp/.mcp.json.",
    async () => {
        if (!existsSync(MCP_CONFIG)) {
            return "No mcp/.mcp.json yet — run `npx financial-services mcp enable <name>` to seed it from the template.";
        }
        try {
            const cfg = JSON.parse(await readFile(MCP_CONFIG, "utf8"));
            const servers = Object.entries(cfg.mcpServers || {});
            const enabled = servers.filter(([, v]) => !v.disabled).map(([k]) => k);
            const disabled = servers.filter(([, v]) => v.disabled).map(([k]) => k);
            return [
                `# financial-services MCP connectors`,
                ``,
                `**Enabled (${enabled.length}):** ${enabled.join(", ") || "(none)"}`,
                `**Disabled (${disabled.length}):** ${disabled.join(", ") || "(none)"}`,
                ``,
                `Toggle with \`npx financial-services mcp enable|disable <name>\`.`,
            ].join("\n");
        } catch (err) {
            return { textResultForLlm: `Failed to read MCP config: ${err.message}`, resultType: "failure" };
        }
    },
));

export const tools = builtTools;

export const inventoryCounts = {
    specialists: inventory.specialists.length,
    verticals: inventory.verticals.length,
    cmdAgents: inventory.cmdAgents.length,
    cmdSkills: inventory.cmdSkills.length,
    tools: builtTools.length,
};

export const presence =
    `[financial-services] The Claude for Financial Services extension is LOADED in this session ` +
    `(${inventoryCounts.specialists} specialists, ${inventoryCounts.verticals} verticals, ` +
    `${inventoryCounts.cmdAgents} command-agents, ${inventoryCounts.tools} tools). ` +
    `Discovery: call \`fs_capabilities\` for the full map; \`fs_instructions\` for compliance posture; ` +
    `\`fs_mcp_status\` for enabled data connectors. ` +
    `Tool naming: \`fs_<slug>_role\` loads an agent system prompt, \`fs_<slug>_skill_<name>\` loads a skill. ` +
    `When the user mentions investment banking, equity research, private equity, wealth management, ` +
    `fund admin, KYC/AML, earnings, valuation, comps, DCF, LBO, or pitch decks — call \`fs_capabilities\` first.`;
